apply plugin: 'com.android.application'

android {
    namespace 'info.staticfree.android.twentyfourhour.wear'
    compileSdkVersion 34

    defaultConfig {
        applicationId "info.staticfree.android.twentyfourhour.wear"
        // Watch Face Format v1 requires Wear OS 4 (API 33)
        minSdkVersion 33
        targetSdkVersion 34
        versionCode 501
        versionName "1.2.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {

        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.android.support:wearable:2.9.0'
    implementation 'com.google.android.gms:play-services-wearable:20.0.1'
    implementation 'com.google.android.gms:play-services-location:21.3.0'
    implementation 'androidx.palette:palette:1.0.0'
    implementation 'androidx.wear:wear:1.3.0'
    implementation project(':lib')
    
    compileOnly 'com.google.android.wearable:wearable:2.9.0'
}
