#!/usr/bin/env python3
"""Generates the 24h dial (numbers, ticks, pips, sun and moon) for the Watch Face Format face.

The output is spliced into wear/src/main/res/raw/watchface.xml between the GENERATED DIAL markers.

WFF has no loops, so each tick, pip and number has to be written out. Geometry comes from the
original artwork (extra/clock_face_moto_360.svg, a 1120px canvas centered at 560,560), scaled to
the 450px watch face.

Usage (from anywhere; needs only the Python 3 standard library):
    python3 extra/generate_dial.py
"""

import math
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

WATCH_FACE = Path(__file__).resolve().parent.parent / "wear/src/main/res/raw/watchface.xml"
BEGIN_MARKER = "<!-- BEGIN GENERATED DIAL -->"
END_MARKER = "<!-- END GENERATED DIAL -->"

SIZE = 450
C = SIZE / 2
SVG_SCALE = SIZE / 1120

# Colors. The accent comes from the user's choice in the watch face editor.
ACCENT = "[CONFIGURATION.accent]"
DISC_COLOR = "#FF616161"  # the original #797979, dimmed 20% for OLED screens
HOUR_COLOR = "#94FFFFFF"
MINUTE_LABEL_COLOR = "#DDFFFFFF"
MINUTE_TICK_COLOR = "#8BF2F2F2"
FONT = "dejavu_sans_mono"

# Dimensions, in 450px units.
DISC_RADIUS = 340.04 * SVG_SCALE
HOUR_RADIUS = 175.5
HOUR_FONT_SIZE = 26
MINUTE_RADIUS = 212
MINUTE_FONT_SIZE = 12
TICK_INNER = 517.2 * SVG_SCALE
TICK_OUTER = 535.4 * SVG_SCALE
TICK_THICKNESS = 4.6 * SVG_SCALE
PIP_RADIUS = 373.2 * SVG_SCALE
PIP_SIZE = 11.07 * SVG_SCALE
PIP_CORNER = 1.48 * SVG_SCALE
ICON_STROKE = 5.5 * SVG_SCALE


def f(value):
    """Formats a number with at most two decimal places and no trailing zeros."""
    rounded = Decimal(format(value, ".15g")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    text = format(rounded, "f").rstrip("0").rstrip(".")
    return "0" if text in ("", "-0") else text


def polar(radius, degrees, cx=C, cy=C):
    """Point at a distance from (cx, cy), at a WFF angle (degrees clockwise from 12 o'clock)."""
    radians = math.radians(degrees)
    return cx + radius * math.sin(radians), cy - radius * math.cos(radians)


def hour_angle(hour):
    """24h dial: hour h is at h * 15 + 180 degrees, so midnight is at the bottom."""
    return (hour * 15 + 180) % 360


def text(label, x, y, width, height, font_size, color):
    # Part positions and sizes must be whole numbers.
    width = round(width)
    height = round(height)
    left = round(x - width / 2)
    top = round(y - height / 2)
    return f"""\
        <PartText x="{left}" y="{top}" width="{width}" height="{height}">
            <Text align="CENTER">
                <Font family="{FONT}" size="{f(font_size)}" color="{color}">{label}</Font>
            </Text>
        </PartText>"""


def hidden_in_ambient(name, parts):
    """Groups parts so they're hidden in ambient (always-on) mode, keeping that mode simple."""
    body = "\n".join("    " + row for part in parts for row in part.split("\n"))
    return f"""\
        <Group x="0" y="0" width="{SIZE}" height="{SIZE}" name="{name}">
            <Variant mode="AMBIENT" target="alpha" value="0" />
{body}
        </Group>"""


def line(start, end, color, thickness):
    return (f'            <Line startX="{f(start[0])}" startY="{f(start[1])}" '
            f'endX="{f(end[0])}" endY="{f(end[1])}"><Stroke color="{color}" '
            f'thickness="{f(thickness)}" cap="BUTT" /></Line>')


def moon_arc(svg_x, svg_y, svg_radius, start, end):
    x = C + (svg_x - 560) * SVG_SCALE
    y = C + (svg_y - 560) * SVG_SCALE
    d = f(2 * svg_radius * SVG_SCALE)
    return (f'            <Arc centerX="{f(x)}" centerY="{f(y)}" width="{d}" height="{d}" '
            f'startAngle="{f(start)}" endAngle="{f(end)}"><Stroke color="{ACCENT}" '
            f'thickness="{f(ICON_STROKE)}" cap="ROUND" /></Arc>')


def generate_dial():
    out = ["        <!-- Generated by extra/generate_dial.py; edit that instead. -->"]

    # Grey disc behind the sun shading. The rest of the dial is the scene's black background.
    d = f(DISC_RADIUS * 2)
    o = f(C - DISC_RADIUS)
    out.append(f"""\
        <PartDraw x="0" y="0" width="{SIZE}" height="{SIZE}" name="disc">
            <Ellipse x="{o}" y="{o}" width="{d}" height="{d}">
                <Fill color="{DISC_COLOR}" />
            </Ellipse>
        </PartDraw>""")

    # Minute ticks, except where there's a minute label. Hidden in ambient.
    out.append(f'        <PartDraw x="0" y="0" width="{SIZE}" height="{SIZE}" name="minute_ticks">')
    out.append('            <Variant mode="AMBIENT" target="alpha" value="0" />')
    for minute in range(60):
        if minute % 5 == 0:
            continue
        out.append(line(polar(TICK_INNER, minute * 6), polar(TICK_OUTER, minute * 6),
                        MINUTE_TICK_COLOR, TICK_THICKNESS))
    out.append("        </PartDraw>")

    # Minute labels every five minutes. Hidden in ambient.
    labels = []
    for minute in range(0, 60, 5):
        x, y = polar(MINUTE_RADIUS, minute * 6)
        labels.append(text(f"{minute:02d}", x, y, 24, MINUTE_FONT_SIZE * 1.3, MINUTE_FONT_SIZE,
                           MINUTE_LABEL_COLOR))
    out.append(hidden_in_ambient("minute_labels", labels))

    # Accent pips on each hour: small rounded squares, rotated to face the center.
    pip_x = f(C - PIP_SIZE / 2)
    pip_y = f(C - PIP_RADIUS - PIP_SIZE / 2)
    for hour in range(24):
        out.append(f"""\
        <PartDraw x="0" y="0" width="{SIZE}" height="{SIZE}" angle="{hour * 15}" name="pip_{hour}">
            <RoundRectangle x="{pip_x}" y="{pip_y}" width="{f(PIP_SIZE)}" height="{f(PIP_SIZE)}" cornerRadiusX="{f(PIP_CORNER)}" cornerRadiusY="{f(PIP_CORNER)}">
                <Fill color="{ACCENT}" />
            </RoundRectangle>
        </PartDraw>""")

    # Hour numbers; noon and midnight get the sun and moon instead. Hidden in ambient, where the
    # pips, sun and moon are enough to read the dial.
    numbers = []
    for hour in range(1, 24):
        if hour == 12:
            continue
        x, y = polar(HOUR_RADIUS, hour_angle(hour))
        numbers.append(text(f"{hour:02d}", x, y, 44, HOUR_FONT_SIZE * 1.2, HOUR_FONT_SIZE,
                            HOUR_COLOR))
    out.append(hidden_in_ambient("hour_numbers", numbers))

    # Sun at noon: a ring with eight rays.
    sun_x, sun_y = polar((560 - 106.67) * SVG_SCALE, hour_angle(12))
    ring_radius = 18.15 * SVG_SCALE
    ray_inner = 28.5 * SVG_SCALE
    ray_outer = 50.7 * SVG_SCALE
    ring_d = f(ring_radius * 2)
    out.append(f'        <PartDraw x="0" y="0" width="{SIZE}" height="{SIZE}" name="sun">')
    out.append(f'            <Ellipse x="{f(sun_x - ring_radius)}" y="{f(sun_y - ring_radius)}" '
               f'width="{ring_d}" height="{ring_d}"><Stroke color="{ACCENT}" '
               f'thickness="{f(ICON_STROKE)}" /></Ellipse>')
    for ray in range(8):
        out.append(line(polar(ray_inner, ray * 45, sun_x, sun_y),
                        polar(ray_outer, ray * 45, sun_x, sun_y), ACCENT, ICON_STROKE))
    out.append("        </PartDraw>")

    # Moon at midnight: a crescent outline made of two arcs that meet at the tips. The outer
    # (left) arc and inner (right) arc are on circles offset horizontally from each other.
    out.append(f'        <PartDraw x="0" y="0" width="{SIZE}" height="{SIZE}" name="moon">')
    out.append(moon_arc(578, 1006, 45.75, 171.7, 368.3))
    out.append(moon_arc(618, 1006, 56.25, 216.4, 323.6))
    out.append("        </PartDraw>")

    return "\n".join(out) + "\n"


def main():
    xml = WATCH_FACE.read_text(encoding="utf-8")
    begin = xml.find(BEGIN_MARKER)
    end = xml.find(END_MARKER)
    if begin < 0 or end < begin:
        raise SystemExit(f"Couldn't find the GENERATED DIAL markers in {WATCH_FACE}")

    xml = (xml[:begin + len(BEGIN_MARKER)] + "\n" + generate_dial() + "        " + xml[end:])
    WATCH_FACE.write_text(xml, encoding="utf-8", newline="\n")
    print(f"Updated {WATCH_FACE}")


if __name__ == "__main__":
    main()
