apply plugin: 'com.android.application'

android {
    namespace 'info.staticfree.android.twentyfourhour.wearphone'
    compileSdkVersion 34

    defaultConfig {
        applicationId "info.staticfree.android.twentyfourhour.wear"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 7
        versionName "1.2.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix '.debug'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.android.gms:play-services-wearable:20.0.1'
    implementation project(':wear')
}
